{{- if .Release.IsInstall }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    environment: "{{ .Values.environment }}"
    heritage: {{ .Release.Service }}
    inventoryCode: "{{ .Values.inventoryCode }}"
    productcode: "{{ .Values.productCode }}"
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
spec:
  maxReplicas: {{ .Values.maxUnavailablePods }}
  selector:
    matchLabels: {{ template "name" . }}
      app: {{ template "name" }}
      release: {{ .Release.Name }}
{{- end }}
