apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: front-envoy
  name: front-envoy
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  - name: "8001"
    port: 8001
    targetPort: 8001
  - name: "8081"
    port: 8081
    targetPort: 8081
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    io.kompose.service: front-envoy
status:
  loadBalancer: {}
